# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kali/projectos/BlueBoy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kali/projectos/BlueBoy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kali/projectos/BlueBoy/CMakeFiles /home/kali/projectos/BlueBoy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kali/projectos/BlueBoy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/kali/projectos/BlueBoy/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blueboy

# Build rule for target.
blueboy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blueboy
.PHONY : blueboy

# fast build rule for target.
blueboy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/build
.PHONY : blueboy/fast

src/core/config.o: src/core/config.cpp.o
.PHONY : src/core/config.o

# target to build an object file
src/core/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/config.cpp.o
.PHONY : src/core/config.cpp.o

src/core/config.i: src/core/config.cpp.i
.PHONY : src/core/config.i

# target to preprocess a source file
src/core/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/config.cpp.i
.PHONY : src/core/config.cpp.i

src/core/config.s: src/core/config.cpp.s
.PHONY : src/core/config.s

# target to generate assembly for a file
src/core/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/config.cpp.s
.PHONY : src/core/config.cpp.s

src/core/framework.o: src/core/framework.cpp.o
.PHONY : src/core/framework.o

# target to build an object file
src/core/framework.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/framework.cpp.o
.PHONY : src/core/framework.cpp.o

src/core/framework.i: src/core/framework.cpp.i
.PHONY : src/core/framework.i

# target to preprocess a source file
src/core/framework.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/framework.cpp.i
.PHONY : src/core/framework.cpp.i

src/core/framework.s: src/core/framework.cpp.s
.PHONY : src/core/framework.s

# target to generate assembly for a file
src/core/framework.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/framework.cpp.s
.PHONY : src/core/framework.cpp.s

src/core/logger.o: src/core/logger.cpp.o
.PHONY : src/core/logger.o

# target to build an object file
src/core/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/logger.cpp.o
.PHONY : src/core/logger.cpp.o

src/core/logger.i: src/core/logger.cpp.i
.PHONY : src/core/logger.i

# target to preprocess a source file
src/core/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/logger.cpp.i
.PHONY : src/core/logger.cpp.i

src/core/logger.s: src/core/logger.cpp.s
.PHONY : src/core/logger.s

# target to generate assembly for a file
src/core/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/logger.cpp.s
.PHONY : src/core/logger.cpp.s

src/core/module.o: src/core/module.cpp.o
.PHONY : src/core/module.o

# target to build an object file
src/core/module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/module.cpp.o
.PHONY : src/core/module.cpp.o

src/core/module.i: src/core/module.cpp.i
.PHONY : src/core/module.i

# target to preprocess a source file
src/core/module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/module.cpp.i
.PHONY : src/core/module.cpp.i

src/core/module.s: src/core/module.cpp.s
.PHONY : src/core/module.s

# target to generate assembly for a file
src/core/module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/core/module.cpp.s
.PHONY : src/core/module.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/modules/dos/bluesmack.o: src/modules/dos/bluesmack.cpp.o
.PHONY : src/modules/dos/bluesmack.o

# target to build an object file
src/modules/dos/bluesmack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/bluesmack.cpp.o
.PHONY : src/modules/dos/bluesmack.cpp.o

src/modules/dos/bluesmack.i: src/modules/dos/bluesmack.cpp.i
.PHONY : src/modules/dos/bluesmack.i

# target to preprocess a source file
src/modules/dos/bluesmack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/bluesmack.cpp.i
.PHONY : src/modules/dos/bluesmack.cpp.i

src/modules/dos/bluesmack.s: src/modules/dos/bluesmack.cpp.s
.PHONY : src/modules/dos/bluesmack.s

# target to generate assembly for a file
src/modules/dos/bluesmack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/bluesmack.cpp.s
.PHONY : src/modules/dos/bluesmack.cpp.s

src/modules/dos/braktooth.o: src/modules/dos/braktooth.cpp.o
.PHONY : src/modules/dos/braktooth.o

# target to build an object file
src/modules/dos/braktooth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/braktooth.cpp.o
.PHONY : src/modules/dos/braktooth.cpp.o

src/modules/dos/braktooth.i: src/modules/dos/braktooth.cpp.i
.PHONY : src/modules/dos/braktooth.i

# target to preprocess a source file
src/modules/dos/braktooth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/braktooth.cpp.i
.PHONY : src/modules/dos/braktooth.cpp.i

src/modules/dos/braktooth.s: src/modules/dos/braktooth.cpp.s
.PHONY : src/modules/dos/braktooth.s

# target to generate assembly for a file
src/modules/dos/braktooth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/braktooth.cpp.s
.PHONY : src/modules/dos/braktooth.cpp.s

src/modules/dos/l2cap_flood.o: src/modules/dos/l2cap_flood.cpp.o
.PHONY : src/modules/dos/l2cap_flood.o

# target to build an object file
src/modules/dos/l2cap_flood.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/l2cap_flood.cpp.o
.PHONY : src/modules/dos/l2cap_flood.cpp.o

src/modules/dos/l2cap_flood.i: src/modules/dos/l2cap_flood.cpp.i
.PHONY : src/modules/dos/l2cap_flood.i

# target to preprocess a source file
src/modules/dos/l2cap_flood.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/l2cap_flood.cpp.i
.PHONY : src/modules/dos/l2cap_flood.cpp.i

src/modules/dos/l2cap_flood.s: src/modules/dos/l2cap_flood.cpp.s
.PHONY : src/modules/dos/l2cap_flood.s

# target to generate assembly for a file
src/modules/dos/l2cap_flood.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/dos/l2cap_flood.cpp.s
.PHONY : src/modules/dos/l2cap_flood.cpp.s

src/modules/exploitation/blueborne.o: src/modules/exploitation/blueborne.cpp.o
.PHONY : src/modules/exploitation/blueborne.o

# target to build an object file
src/modules/exploitation/blueborne.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/blueborne.cpp.o
.PHONY : src/modules/exploitation/blueborne.cpp.o

src/modules/exploitation/blueborne.i: src/modules/exploitation/blueborne.cpp.i
.PHONY : src/modules/exploitation/blueborne.i

# target to preprocess a source file
src/modules/exploitation/blueborne.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/blueborne.cpp.i
.PHONY : src/modules/exploitation/blueborne.cpp.i

src/modules/exploitation/blueborne.s: src/modules/exploitation/blueborne.cpp.s
.PHONY : src/modules/exploitation/blueborne.s

# target to generate assembly for a file
src/modules/exploitation/blueborne.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/blueborne.cpp.s
.PHONY : src/modules/exploitation/blueborne.cpp.s

src/modules/exploitation/blueducky.o: src/modules/exploitation/blueducky.cpp.o
.PHONY : src/modules/exploitation/blueducky.o

# target to build an object file
src/modules/exploitation/blueducky.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/blueducky.cpp.o
.PHONY : src/modules/exploitation/blueducky.cpp.o

src/modules/exploitation/blueducky.i: src/modules/exploitation/blueducky.cpp.i
.PHONY : src/modules/exploitation/blueducky.i

# target to preprocess a source file
src/modules/exploitation/blueducky.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/blueducky.cpp.i
.PHONY : src/modules/exploitation/blueducky.cpp.i

src/modules/exploitation/blueducky.s: src/modules/exploitation/blueducky.cpp.s
.PHONY : src/modules/exploitation/blueducky.s

# target to generate assembly for a file
src/modules/exploitation/blueducky.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/blueducky.cpp.s
.PHONY : src/modules/exploitation/blueducky.cpp.s

src/modules/exploitation/bluefrag.o: src/modules/exploitation/bluefrag.cpp.o
.PHONY : src/modules/exploitation/bluefrag.o

# target to build an object file
src/modules/exploitation/bluefrag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/bluefrag.cpp.o
.PHONY : src/modules/exploitation/bluefrag.cpp.o

src/modules/exploitation/bluefrag.i: src/modules/exploitation/bluefrag.cpp.i
.PHONY : src/modules/exploitation/bluefrag.i

# target to preprocess a source file
src/modules/exploitation/bluefrag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/bluefrag.cpp.i
.PHONY : src/modules/exploitation/bluefrag.cpp.i

src/modules/exploitation/bluefrag.s: src/modules/exploitation/bluefrag.cpp.s
.PHONY : src/modules/exploitation/bluefrag.s

# target to generate assembly for a file
src/modules/exploitation/bluefrag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/bluefrag.cpp.s
.PHONY : src/modules/exploitation/bluefrag.cpp.s

src/modules/exploitation/knob.o: src/modules/exploitation/knob.cpp.o
.PHONY : src/modules/exploitation/knob.o

# target to build an object file
src/modules/exploitation/knob.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/knob.cpp.o
.PHONY : src/modules/exploitation/knob.cpp.o

src/modules/exploitation/knob.i: src/modules/exploitation/knob.cpp.i
.PHONY : src/modules/exploitation/knob.i

# target to preprocess a source file
src/modules/exploitation/knob.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/knob.cpp.i
.PHONY : src/modules/exploitation/knob.cpp.i

src/modules/exploitation/knob.s: src/modules/exploitation/knob.cpp.s
.PHONY : src/modules/exploitation/knob.s

# target to generate assembly for a file
src/modules/exploitation/knob.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/knob.cpp.s
.PHONY : src/modules/exploitation/knob.cpp.s

src/modules/exploitation/sweyντooth.o: src/modules/exploitation/sweyντooth.cpp.o
.PHONY : src/modules/exploitation/sweyντooth.o

# target to build an object file
src/modules/exploitation/sweyντooth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/sweyντooth.cpp.o
.PHONY : src/modules/exploitation/sweyντooth.cpp.o

src/modules/exploitation/sweyντooth.i: src/modules/exploitation/sweyντooth.cpp.i
.PHONY : src/modules/exploitation/sweyντooth.i

# target to preprocess a source file
src/modules/exploitation/sweyντooth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/sweyντooth.cpp.i
.PHONY : src/modules/exploitation/sweyντooth.cpp.i

src/modules/exploitation/sweyντooth.s: src/modules/exploitation/sweyντooth.cpp.s
.PHONY : src/modules/exploitation/sweyντooth.s

# target to generate assembly for a file
src/modules/exploitation/sweyντooth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/exploitation/sweyντooth.cpp.s
.PHONY : src/modules/exploitation/sweyντooth.cpp.s

src/modules/mitm/bias.o: src/modules/mitm/bias.cpp.o
.PHONY : src/modules/mitm/bias.o

# target to build an object file
src/modules/mitm/bias.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/mitm/bias.cpp.o
.PHONY : src/modules/mitm/bias.cpp.o

src/modules/mitm/bias.i: src/modules/mitm/bias.cpp.i
.PHONY : src/modules/mitm/bias.i

# target to preprocess a source file
src/modules/mitm/bias.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/mitm/bias.cpp.i
.PHONY : src/modules/mitm/bias.cpp.i

src/modules/mitm/bias.s: src/modules/mitm/bias.cpp.s
.PHONY : src/modules/mitm/bias.s

# target to generate assembly for a file
src/modules/mitm/bias.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/mitm/bias.cpp.s
.PHONY : src/modules/mitm/bias.cpp.s

src/modules/mitm/bluejacking.o: src/modules/mitm/bluejacking.cpp.o
.PHONY : src/modules/mitm/bluejacking.o

# target to build an object file
src/modules/mitm/bluejacking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/mitm/bluejacking.cpp.o
.PHONY : src/modules/mitm/bluejacking.cpp.o

src/modules/mitm/bluejacking.i: src/modules/mitm/bluejacking.cpp.i
.PHONY : src/modules/mitm/bluejacking.i

# target to preprocess a source file
src/modules/mitm/bluejacking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/mitm/bluejacking.cpp.i
.PHONY : src/modules/mitm/bluejacking.cpp.i

src/modules/mitm/bluejacking.s: src/modules/mitm/bluejacking.cpp.s
.PHONY : src/modules/mitm/bluejacking.s

# target to generate assembly for a file
src/modules/mitm/bluejacking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/mitm/bluejacking.cpp.s
.PHONY : src/modules/mitm/bluejacking.cpp.s

src/modules/persistence/bluebug.o: src/modules/persistence/bluebug.cpp.o
.PHONY : src/modules/persistence/bluebug.o

# target to build an object file
src/modules/persistence/bluebug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/persistence/bluebug.cpp.o
.PHONY : src/modules/persistence/bluebug.cpp.o

src/modules/persistence/bluebug.i: src/modules/persistence/bluebug.cpp.i
.PHONY : src/modules/persistence/bluebug.i

# target to preprocess a source file
src/modules/persistence/bluebug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/persistence/bluebug.cpp.i
.PHONY : src/modules/persistence/bluebug.cpp.i

src/modules/persistence/bluebug.s: src/modules/persistence/bluebug.cpp.s
.PHONY : src/modules/persistence/bluebug.s

# target to generate assembly for a file
src/modules/persistence/bluebug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/persistence/bluebug.cpp.s
.PHONY : src/modules/persistence/bluebug.cpp.s

src/modules/privesc/bluecrack.o: src/modules/privesc/bluecrack.cpp.o
.PHONY : src/modules/privesc/bluecrack.o

# target to build an object file
src/modules/privesc/bluecrack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/privesc/bluecrack.cpp.o
.PHONY : src/modules/privesc/bluecrack.cpp.o

src/modules/privesc/bluecrack.i: src/modules/privesc/bluecrack.cpp.i
.PHONY : src/modules/privesc/bluecrack.i

# target to preprocess a source file
src/modules/privesc/bluecrack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/privesc/bluecrack.cpp.i
.PHONY : src/modules/privesc/bluecrack.cpp.i

src/modules/privesc/bluecrack.s: src/modules/privesc/bluecrack.cpp.s
.PHONY : src/modules/privesc/bluecrack.s

# target to generate assembly for a file
src/modules/privesc/bluecrack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/privesc/bluecrack.cpp.s
.PHONY : src/modules/privesc/bluecrack.cpp.s

src/modules/reconnaissance/bluesnarf.o: src/modules/reconnaissance/bluesnarf.cpp.o
.PHONY : src/modules/reconnaissance/bluesnarf.o

# target to build an object file
src/modules/reconnaissance/bluesnarf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/reconnaissance/bluesnarf.cpp.o
.PHONY : src/modules/reconnaissance/bluesnarf.cpp.o

src/modules/reconnaissance/bluesnarf.i: src/modules/reconnaissance/bluesnarf.cpp.i
.PHONY : src/modules/reconnaissance/bluesnarf.i

# target to preprocess a source file
src/modules/reconnaissance/bluesnarf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/reconnaissance/bluesnarf.cpp.i
.PHONY : src/modules/reconnaissance/bluesnarf.cpp.i

src/modules/reconnaissance/bluesnarf.s: src/modules/reconnaissance/bluesnarf.cpp.s
.PHONY : src/modules/reconnaissance/bluesnarf.s

# target to generate assembly for a file
src/modules/reconnaissance/bluesnarf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/reconnaissance/bluesnarf.cpp.s
.PHONY : src/modules/reconnaissance/bluesnarf.cpp.s

src/modules/reconnaissance/bluesniff.o: src/modules/reconnaissance/bluesniff.cpp.o
.PHONY : src/modules/reconnaissance/bluesniff.o

# target to build an object file
src/modules/reconnaissance/bluesniff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/reconnaissance/bluesniff.cpp.o
.PHONY : src/modules/reconnaissance/bluesniff.cpp.o

src/modules/reconnaissance/bluesniff.i: src/modules/reconnaissance/bluesniff.cpp.i
.PHONY : src/modules/reconnaissance/bluesniff.i

# target to preprocess a source file
src/modules/reconnaissance/bluesniff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/reconnaissance/bluesniff.cpp.i
.PHONY : src/modules/reconnaissance/bluesniff.cpp.i

src/modules/reconnaissance/bluesniff.s: src/modules/reconnaissance/bluesniff.cpp.s
.PHONY : src/modules/reconnaissance/bluesniff.s

# target to generate assembly for a file
src/modules/reconnaissance/bluesniff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blueboy.dir/build.make CMakeFiles/blueboy.dir/src/modules/reconnaissance/bluesniff.cpp.s
.PHONY : src/modules/reconnaissance/bluesniff.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... blueboy"
	@echo "... src/core/config.o"
	@echo "... src/core/config.i"
	@echo "... src/core/config.s"
	@echo "... src/core/framework.o"
	@echo "... src/core/framework.i"
	@echo "... src/core/framework.s"
	@echo "... src/core/logger.o"
	@echo "... src/core/logger.i"
	@echo "... src/core/logger.s"
	@echo "... src/core/module.o"
	@echo "... src/core/module.i"
	@echo "... src/core/module.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/modules/dos/bluesmack.o"
	@echo "... src/modules/dos/bluesmack.i"
	@echo "... src/modules/dos/bluesmack.s"
	@echo "... src/modules/dos/braktooth.o"
	@echo "... src/modules/dos/braktooth.i"
	@echo "... src/modules/dos/braktooth.s"
	@echo "... src/modules/dos/l2cap_flood.o"
	@echo "... src/modules/dos/l2cap_flood.i"
	@echo "... src/modules/dos/l2cap_flood.s"
	@echo "... src/modules/exploitation/blueborne.o"
	@echo "... src/modules/exploitation/blueborne.i"
	@echo "... src/modules/exploitation/blueborne.s"
	@echo "... src/modules/exploitation/blueducky.o"
	@echo "... src/modules/exploitation/blueducky.i"
	@echo "... src/modules/exploitation/blueducky.s"
	@echo "... src/modules/exploitation/bluefrag.o"
	@echo "... src/modules/exploitation/bluefrag.i"
	@echo "... src/modules/exploitation/bluefrag.s"
	@echo "... src/modules/exploitation/knob.o"
	@echo "... src/modules/exploitation/knob.i"
	@echo "... src/modules/exploitation/knob.s"
	@echo "... src/modules/exploitation/sweyντooth.o"
	@echo "... src/modules/exploitation/sweyντooth.i"
	@echo "... src/modules/exploitation/sweyντooth.s"
	@echo "... src/modules/mitm/bias.o"
	@echo "... src/modules/mitm/bias.i"
	@echo "... src/modules/mitm/bias.s"
	@echo "... src/modules/mitm/bluejacking.o"
	@echo "... src/modules/mitm/bluejacking.i"
	@echo "... src/modules/mitm/bluejacking.s"
	@echo "... src/modules/persistence/bluebug.o"
	@echo "... src/modules/persistence/bluebug.i"
	@echo "... src/modules/persistence/bluebug.s"
	@echo "... src/modules/privesc/bluecrack.o"
	@echo "... src/modules/privesc/bluecrack.i"
	@echo "... src/modules/privesc/bluecrack.s"
	@echo "... src/modules/reconnaissance/bluesnarf.o"
	@echo "... src/modules/reconnaissance/bluesnarf.i"
	@echo "... src/modules/reconnaissance/bluesnarf.s"
	@echo "... src/modules/reconnaissance/bluesniff.o"
	@echo "... src/modules/reconnaissance/bluesniff.i"
	@echo "... src/modules/reconnaissance/bluesniff.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/kali/projectos/BlueBoy/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

